/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Room;
import model.TypeRoom;
import model.User;
import model.Zone;
/**
 *
 * @author VanTinh
 */
public class DangNhapNope extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapNope
     */
     private ArrayList<Room> listRoom;
    private ArrayList<Zone> listZone;
    private ArrayList<TypeRoom> listType;
    private ArrayList<Zone> listZoneNam;
    private ArrayList<Zone> listZoneNu;
    private ArrayList<TypeRoom> listCost;
       public static String roomDKy,zoneDky,typeDky,gioiTinh,kiDangKy;
       public static int costRoom,thoiHanDky;
       public static String IDUs;
       public static String nganh;
    private ArrayList<User> list;
    public DangNhapNope() {
        initComponents();
         list=new DAO().getListUser();
         listRoom=new DAO().getListRoom();
        listType=new DAO().getListTypeRoom();
        listZone=new DAO().getListZone();
        listZoneNam=new DAO().getListZoneNam();
        listZoneNu=new DAO().getListZoneNu();
         setResizable(false);
         jAcc.setText("N19DCPT064");
         jPass.setText("03092001");
         setLocation(200, 150);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nganhComboBox = new javax.swing.JComboBox<>();
        femaleCheck = new javax.swing.JCheckBox();
        maleCheck = new javax.swing.JCheckBox();
        zoneComboBox = new javax.swing.JComboBox<>();
        typeRoomComboBox = new javax.swing.JComboBox<>();
        roomComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        motKiCheck = new javax.swing.JCheckBox();
        haiKiCheck = new javax.swing.JCheckBox();
        baKiCheck = new javax.swing.JCheckBox();
        motKiComboBox = new javax.swing.JComboBox<>();
        haiKiComboBox = new javax.swing.JComboBox<>();
        dkyroomP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jAcc = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        signInP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_home_25px_1.png")); // NOI18N
        jLabel5.setText("Room Registration");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_permanent_job_15px_2.png")); // NOI18N
        jLabel7.setText("Majors");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_male_female_user_group_15px.png")); // NOI18N
        jLabel8.setText("Sex");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_flag_filled_20px.png")); // NOI18N
        jLabel9.setText("Zone");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_business_girl_hotel_room_15px_1.png")); // NOI18N
        jLabel10.setText("Type ");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_hotel_bed_15px.png")); // NOI18N
        jLabel11.setText("Room");

        nganhComboBox.setBackground(new java.awt.Color(97, 212, 195));
        nganhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nganhComboBox.setForeground(new java.awt.Color(0, 0, 0));
        nganhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Công Nghệ Đa Phương Tiện", "Marketing", "Kế Toán", "Quản Trị Kinh Doanh", "Điện Tử Viễn Thông", "An Toàn Thông Tin" }));
        nganhComboBox.setBorder(null);

        femaleCheck.setBackground(new java.awt.Color(97, 212, 195));
        femaleCheck.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        femaleCheck.setForeground(new java.awt.Color(255, 255, 255));
        femaleCheck.setText("Female");
        femaleCheck.setBorder(null);
        femaleCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleCheckMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                femaleCheckMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                femaleCheckMousePressed(evt);
            }
        });

        maleCheck.setBackground(new java.awt.Color(97, 212, 195));
        maleCheck.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        maleCheck.setForeground(new java.awt.Color(255, 255, 255));
        maleCheck.setText("Male");
        maleCheck.setBorder(null);
        maleCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleCheckMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maleCheckMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maleCheckMousePressed(evt);
            }
        });
        maleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheckActionPerformed(evt);
            }
        });

        zoneComboBox.setBackground(new java.awt.Color(97, 212, 195));
        zoneComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        zoneComboBox.setForeground(new java.awt.Color(0, 0, 0));
        zoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneComboBoxActionPerformed(evt);
            }
        });

        typeRoomComboBox.setBackground(new java.awt.Color(97, 212, 195));
        typeRoomComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        typeRoomComboBox.setForeground(new java.awt.Color(0, 0, 0));
        typeRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Service type 1 - 420k/1 month", "Service type 2 - 330k/1 month", "Normal - 120k/1 month" }));
        typeRoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRoomComboBoxActionPerformed(evt);
            }
        });

        roomComboBox.setBackground(new java.awt.Color(97, 212, 195));
        roomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("If You Don't Have Room. Please Registration Below!");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Welcom To My Dorm");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_planner_20px_2.png")); // NOI18N
        jLabel14.setText("Time");

        motKiCheck.setBackground(new java.awt.Color(97, 212, 195));
        motKiCheck.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        motKiCheck.setForeground(new java.awt.Color(255, 255, 255));
        motKiCheck.setText("1 Semester");
        motKiCheck.setBorder(null);
        motKiCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                motKiCheckMouseClicked(evt);
            }
        });
        motKiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motKiCheckActionPerformed(evt);
            }
        });

        haiKiCheck.setBackground(new java.awt.Color(97, 212, 195));
        haiKiCheck.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        haiKiCheck.setForeground(new java.awt.Color(255, 255, 255));
        haiKiCheck.setText("2 Semester");
        haiKiCheck.setBorder(null);
        haiKiCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haiKiCheckMouseClicked(evt);
            }
        });
        haiKiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haiKiCheckActionPerformed(evt);
            }
        });

        baKiCheck.setBackground(new java.awt.Color(97, 212, 195));
        baKiCheck.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        baKiCheck.setForeground(new java.awt.Color(255, 255, 255));
        baKiCheck.setText("3 Semester");
        baKiCheck.setBorder(null);
        baKiCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baKiCheckMouseClicked(evt);
            }
        });
        baKiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baKiCheckActionPerformed(evt);
            }
        });

        motKiComboBox.setBackground(new java.awt.Color(97, 212, 195));
        motKiComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        motKiComboBox.setForeground(new java.awt.Color(0, 0, 0));
        motKiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1 - 5 months", "Semester 2 - 5 months", "Semester 3 - 2 months" }));
        motKiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motKiComboBoxActionPerformed(evt);
            }
        });

        haiKiComboBox.setBackground(new java.awt.Color(97, 212, 195));
        haiKiComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        haiKiComboBox.setForeground(new java.awt.Color(0, 0, 0));
        haiKiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1&2 - 10 months", "Semester 2&3 - 7 months" }));

        dkyroomP.setBackground(new java.awt.Color(36, 47, 65));
        dkyroomP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dkyroomPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dkyroomPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dkyroomPMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RoomResistration");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout dkyroomPLayout = new javax.swing.GroupLayout(dkyroomP);
        dkyroomP.setLayout(dkyroomPLayout);
        dkyroomPLayout.setHorizontalGroup(
            dkyroomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkyroomPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        dkyroomPLayout.setVerticalGroup(
            dkyroomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkyroomPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(motKiCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(haiKiCheck)
                                    .addComponent(baKiCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(motKiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(haiKiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(femaleCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addComponent(nganhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(typeRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dkyroomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nganhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleCheck)
                    .addComponent(femaleCheck))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motKiCheck)
                    .addComponent(motKiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haiKiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haiKiCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(baKiCheck)
                .addGap(34, 34, 34)
                .addComponent(dkyroomP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 560));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MSSV/CMND");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        jAcc.setBackground(new java.awt.Color(36, 47, 65));
        jAcc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jAcc.setForeground(new java.awt.Color(255, 255, 255));
        jAcc.setBorder(null);
        jAcc.setCaretColor(new java.awt.Color(204, 204, 204));

        jPass.setBackground(new java.awt.Color(36, 47, 65));
        jPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPass.setForeground(new java.awt.Color(255, 255, 255));
        jPass.setText("jPasswordField1");
        jPass.setBorder(null);

        signInP.setBackground(new java.awt.Color(97, 212, 195));
        signInP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInPMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SignIn");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout signInPLayout = new javax.swing.GroupLayout(signInP);
        signInP.setLayout(signInPLayout);
        signInPLayout.setHorizontalGroup(
            signInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        signInPLayout.setVerticalGroup(
            signInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_building_50px.png")); // NOI18N
        jLabel6.setText("Ptit's Dorm");

        jCheckBox2.setBackground(new java.awt.Color(36, 47, 65));
        jCheckBox2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("REMEMBER ME");
        jCheckBox2.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAcc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(signInP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(27, 27, 27)
                .addComponent(signInP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 530, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        if(!(maleCheck.isSelected()||femaleCheck.isSelected())){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn giới tính");
        }else{
            if(zoneComboBox.getSelectedIndex()<0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn khu");
            }else{
                if(typeRoomComboBox.getSelectedIndex()<0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn loại dịch vụ");
            }else{
                    if(roomComboBox.getSelectedIndex()<0){
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn phòng");
                    }else{
                        if(!(motKiCheck.isSelected()||haiKiCheck.isSelected()||baKiCheck.isSelected())){
                            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thời gian đăng ký ở");
                        }else{
                            int x=JOptionPane.showConfirmDialog(rootPane, "Xác nhận thông tin phòng muốn đăng ký?");
                            if(x==JOptionPane.YES_OPTION){
                                addThongTinDky();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jLabel3MousePressed
void addThongTinDky(){
    String typeValue=(String)typeRoomComboBox.getSelectedItem();
        String type;
        if(typeValue.equals("Service type 1 - 420k/1 month")) type="dịch vụ loại 1";
        else if(typeValue.equals("Service type 2 - 330k/1 month")) type ="dịch vụ loại 2";
        else type="thường";
        String zoneValue=(String)zoneComboBox.getSelectedItem();
        String roomValue=(String) roomComboBox.getSelectedItem();
    listCost=new DAO().getCost((type));
                                int cost=0;
                                for(TypeRoom a:listCost)
                                {
                                    cost=a.getCost();
                                }
                                if(motKiComboBox.getSelectedIndex()==0)
                                {
                                    costRoom=0;
                                    costRoom=cost*5;
                                    kiDangKy="";
                                    kiDangKy="HK1";
                                }
                                else if(motKiComboBox.getSelectedIndex()==1){
                                    costRoom=0;
                                    costRoom=cost*5;
                                    kiDangKy="";
                                    kiDangKy="HK2";
                                }
                                else if(motKiComboBox.getSelectedIndex()==2){
                                    costRoom=0;
                                    costRoom=cost*2;
                                    kiDangKy="";
                                    kiDangKy="HK3";
                                }
                                if(haiKiCheck.isSelected()&&haiKiComboBox.getSelectedIndex()==0)
                                {
                                    costRoom=0;
                                    costRoom=cost*10;
                                    kiDangKy="";
                                    kiDangKy="HK1-2";
                                }
                                else if(haiKiCheck.isSelected()&&haiKiComboBox.getSelectedIndex()==1){
                                    costRoom=0;
                                    costRoom=cost*7;
                                    kiDangKy="";
                                    kiDangKy="HK2-3";
                                }
                                if(baKiCheck.isSelected())
                                {
                                    costRoom=0;
                                    costRoom=cost*12;
                                    kiDangKy="";
                                    kiDangKy="Cả năm";
                                }
                                nganh=(String)nganhComboBox.getSelectedItem();
                                zoneDky=zoneValue;
                                typeDky=typeValue;
                                roomDKy=roomValue;
                                new DangKyThongTin().setVisible(true);
}
    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        String passUs =String.valueOf(jPass.getPassword());
        boolean check=false;
        int idRole=0;
       for(int i=0;i<list.size();i++)
       {
         if(list.get(i).getIDUs().equals(jAcc.getText())&&list.get(i).getPass().equals(passUs))
         {
             idRole=list.get(i).getIDRole();
             check=true;
         }
       }
        if(check==true){
         JOptionPane.showMessageDialog(rootPane, "Sign In Success!");
            setVisible(false);
            IDUs=jAcc.getText();
            if(idRole==1)
                new SinhVien().setVisible(true);
            else if(idRole==2)
                new Manager().setVisible(true);
                
        }
        else 
             JOptionPane.showMessageDialog(rootPane, "MSSV OR PASSWORD IS NOT CORRECT. PLEASE TRY !");
    }//GEN-LAST:event_jLabel4MousePressed

    private void signInPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseEntered
        // TODO add your handling code here:
        onHover(signInP);
    }//GEN-LAST:event_signInPMouseEntered

    private void signInPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_signInPMouseExited

    private void signInPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseReleased

    }//GEN-LAST:event_signInPMouseReleased

    private void dkyroomPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dkyroomPMouseEntered
        // TODO add your handling code here:
         onHo(dkyroomP);
    }//GEN-LAST:event_dkyroomPMouseEntered

    private void dkyroomPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dkyroomPMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_dkyroomPMouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
       // resetColor(jPanel3);
         resetColor(signInP);
         setColor(dkyroomP);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void maleCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleCheckMouseClicked
        // TODO add your handling code here:
        femaleCheck.setSelected(false);
        if(maleCheck.isSelected()){
        femaleCheck.setSelected(false);
        gioiTinh=maleCheck.getText();
        }
        else {
            gioiTinh="";
            zoneComboBox.removeAllItems();
            roomComboBox.removeAll();
        }
        if(gioiTinh.equals("Male"))
        {
            zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNam.size();i++)
        {
            zoneComboBox.addItem(listZoneNam.get(i).getNameZone());
        }
        }
          if(gioiTinh.equals("Nữ"))
        {
            zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNu.size();i++)
        {
            zoneComboBox.addItem(listZoneNu.get(i).getNameZone());
        }
        }  
    }//GEN-LAST:event_maleCheckMouseClicked

    private void femaleCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleCheckMouseClicked
        // TODO add your handling code here:
        maleCheck.setSelected(false);
        if(femaleCheck.isSelected()){
          maleCheck.setSelected(false);
         gioiTinh=femaleCheck.getText();
        }
        else {
            gioiTinh="";
            zoneComboBox.removeAllItems();
            roomComboBox.removeAll();
        }
        if(gioiTinh.equals("Male"))
        {
            zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNam.size();i++)
        {
            zoneComboBox.addItem(listZoneNam.get(i).getNameZone());
        }
        }
          if(gioiTinh.equals("Female"))
        {
            zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNu.size();i++)
        {
            zoneComboBox.addItem(listZoneNu.get(i).getNameZone());
        }
        }
    }//GEN-LAST:event_femaleCheckMouseClicked

    private void zoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneComboBoxActionPerformed
        // TODO add your handling code here:
      String zone=(String)zoneComboBox.getSelectedItem();
        String sexValue;
        if(maleCheck.isSelected()) sexValue=maleCheck.getText();
        else sexValue=femaleCheck.getText();
        String typeValue=(String)typeRoomComboBox.getSelectedItem();
        int sex,type;
        if(sexValue.equals("Male")){
            sex=1;
        }
        else sex=2;
        if(typeValue.equals("Service type 1 - 420k/1 month")) type=1;
        else if(typeValue.equals("Service type 2 - 330k/1 month")) type =2;
        else type=3;
        setData(sex, zone, type);
    }//GEN-LAST:event_zoneComboBoxActionPerformed

    private void typeRoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRoomComboBoxActionPerformed
        // TODO add your handling code here:
        String zone=(String)zoneComboBox.getSelectedItem();
        String sexValue;
        if(maleCheck.isSelected()) sexValue=maleCheck.getText();
        else sexValue=femaleCheck.getText();
        String typeValue=(String)typeRoomComboBox.getSelectedItem();
        int sex,type;
        if(sexValue.equals("Male")){
            sex=1;
        }
        else sex=2;
        if(typeValue.equals("Service type 1 - 420k/1 month")) type=1;
        else if(typeValue.equals("Service type 2 - 330k/1 month")) type =2;
        else type=3;
        setData(sex, zone, type);
    }//GEN-LAST:event_typeRoomComboBoxActionPerformed

    private void motKiCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motKiCheckMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_motKiCheckMouseClicked

    private void haiKiCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haiKiCheckMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_haiKiCheckMouseClicked

    private void baKiCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baKiCheckMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_baKiCheckMouseClicked

    private void maleCheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleCheckMouseExited
        // TODO add your handling code here:
        //femaleCheck.setSelected(false);
    }//GEN-LAST:event_maleCheckMouseExited

    private void femaleCheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleCheckMouseExited
        // TODO add your handling code here:
        //maleCheck.setSelected(false);
    }//GEN-LAST:event_femaleCheckMouseExited

    private void motKiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motKiCheckActionPerformed
        // TODO add your handling code here:
         if(motKiCheck.isSelected()){
          haiKiCheck.setSelected(false);
          baKiCheck.setSelected(false);
           motKiComboBox.setSelectedIndex(0);
           haiKiComboBox.setSelectedIndex(-1);
         }
    }//GEN-LAST:event_motKiCheckActionPerformed

    private void motKiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motKiComboBoxActionPerformed
        // TODO add your handling code here:
         if(motKiComboBox.getSelectedIndex()>=0){
            motKiCheck.setSelected(true);
            haiKiCheck.setSelected(false);
          baKiCheck.setSelected(false);
        }
    }//GEN-LAST:event_motKiComboBoxActionPerformed

    private void baKiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baKiCheckActionPerformed
        // TODO add your handling code here:
         if(baKiCheck.isSelected()) {
          motKiCheck.setSelected(false);
          motKiComboBox.setSelectedIndex(-1);
          haiKiCheck.setSelected(false);
          haiKiComboBox.setSelectedIndex(-1);
         }
    }//GEN-LAST:event_baKiCheckActionPerformed

    private void haiKiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haiKiCheckActionPerformed
        // TODO add your handling code here:
        if(haiKiCheck.isSelected()) {
            motKiCheck.setSelected(false);
            baKiCheck.setSelected(false);
            motKiComboBox.setSelectedIndex(-1); 
            haiKiComboBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_haiKiCheckActionPerformed

    private void dkyroomPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dkyroomPMousePressed
        // TODO add your handling code here:
         if(!(maleCheck.isSelected()||femaleCheck.isSelected())){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn giới tính");
        }else{
            if(zoneComboBox.getSelectedIndex()<0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn khu");
            }else{
                if(typeRoomComboBox.getSelectedIndex()<0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn loại dịch vụ");
            }else{
                    if(roomComboBox.getSelectedIndex()<0){
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn phòng");
                    }else{
                        if(!(motKiCheck.isSelected()||haiKiCheck.isSelected()||baKiCheck.isSelected())){
                            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thời gian đăng ký ở");
                        }else{
                            int x=JOptionPane.showConfirmDialog(rootPane, "Xác nhận thông tin phòng muốn đăng ký?");
                            if(x==JOptionPane.YES_OPTION){
                                addThongTinDky();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_dkyroomPMousePressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        //setColor(dkyroomP);
        resetColor(signInP);
        setColor(dkyroomP);
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void signInPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMousePressed
        // TODO add your handling code here:
        String passUs =String.valueOf(jPass.getPassword());
        boolean check=false;
        int idRole=0;
       for(int i=0;i<list.size();i++)
       {
         if(list.get(i).getIDUs().equals(jAcc.getText())&&list.get(i).getPass().equals(passUs))
         {
             idRole=list.get(i).getIDRole();
             check=true;
         }
       }
        if(check==true){
         JOptionPane.showMessageDialog(rootPane, "Sign In Success!");
            setVisible(false);
            IDUs=jAcc.getText();
            if(idRole==1)
                new SinhVien().setVisible(true);
            else if(idRole==2)
                new Manager().setVisible(true);
                
        }
        else 
             JOptionPane.showMessageDialog(rootPane, "MSSV OR PASSWORD IS NOT CORRECT. PLEASE TRY !");
    }//GEN-LAST:event_signInPMousePressed

    private void maleCheckMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleCheckMousePressed
        // TODO add your handling code here:
        femaleCheck.setSelected(false);
    }//GEN-LAST:event_maleCheckMousePressed

    private void femaleCheckMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleCheckMousePressed
        // TODO add your handling code here:
        maleCheck.setSelected(false);
    }//GEN-LAST:event_femaleCheckMousePressed

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomComboBoxActionPerformed

    private void maleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void onHover(JPanel panel){
        panel.setBackground(new Color(204,204,255));
    }
    void setColor(JPanel panel){
        panel.setBackground(new Color(36,47,65));
        
    }
   
    void resetColor(JPanel panel){
       
            panel.setBackground(new Color(97,212,195));
        
    }
     void onHo(JPanel panel){
        panel.setBackground(new Color(0,102,102));
    }
    public void setData(int sex, String zone, int typeRoom){
        roomComboBox.removeAllItems();
        ArrayList<Room> arr = new DAO().getDataRoom(sex, zone, typeRoom);
        for (Room room: arr){
            roomComboBox.addItem(room.getNameRoom());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapNope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapNope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapNope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapNope.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapNope().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox baKiCheck;
    private javax.swing.JPanel dkyroomP;
    private javax.swing.JCheckBox femaleCheck;
    private javax.swing.JCheckBox haiKiCheck;
    private javax.swing.JComboBox<String> haiKiComboBox;
    private javax.swing.JTextField jAcc;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox maleCheck;
    private javax.swing.JCheckBox motKiCheck;
    private javax.swing.JComboBox<String> motKiComboBox;
    private javax.swing.JComboBox<String> nganhComboBox;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JPanel signInP;
    private javax.swing.JComboBox<String> typeRoomComboBox;
    private javax.swing.JComboBox<String> zoneComboBox;
    // End of variables declaration//GEN-END:variables
}
