/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Room;
import model.TypeRoom;
import model.User;
import model.Zone;
/**
 *
 * @author VanTinh
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
     private ArrayList<Room> listRoom;
    private ArrayList<Zone> listZone;
    private ArrayList<TypeRoom> listType;
    private ArrayList<Zone> listZoneNam;
    private ArrayList<Zone> listZoneNu;
    private ArrayList<TypeRoom> listCost;
       public static String roomDKy,zoneDky,typeDky,gioiTinh,kiDangKy;
       public static int costRoom,thoiHanDky;
       public static String IDUs;
       public static String nganh;
    private ArrayList<User> list;
    public DangNhap() {
        initComponents();
         list=new DAO().getListUser();
         listRoom=new DAO().getListRoom();
        listType=new DAO().getListTypeRoom();
        listZone=new DAO().getListZone();
        listZoneNam=new DAO().getListZoneNam();
        listZoneNu=new DAO().getListZoneNu();
         setResizable(false);
         jAcc.setText("N19DCPT064");
         jPass.setText("03092001");
         setLocation(200, 150);
         hide_show1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jAcc = new javax.swing.JTextField();
        jPass = new javax.swing.JPasswordField();
        signInP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        signUp = new javax.swing.JLabel();
        daDky = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        xemTT = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        daDky1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        hide_show = new javax.swing.JLabel();
        hide_show1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MSSV/CMND");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 783, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MẬT KHẨU");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, 754, 35));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 208, 360, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 287, 360, 10));

        jAcc.setBackground(new java.awt.Color(36, 47, 65));
        jAcc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jAcc.setForeground(new java.awt.Color(255, 255, 255));
        jAcc.setBorder(null);
        jAcc.setCaretColor(new java.awt.Color(204, 204, 204));
        jAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccActionPerformed(evt);
            }
        });
        jPanel2.add(jAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 183, 360, 24));

        jPass.setBackground(new java.awt.Color(36, 47, 65));
        jPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPass.setForeground(new java.awt.Color(255, 255, 255));
        jPass.setText("jPasswordField1");
        jPass.setBorder(null);
        jPanel2.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 271, 330, -1));

        signInP.setBackground(new java.awt.Color(97, 212, 195));
        signInP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInPMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đăng nhập");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout signInPLayout = new javax.swing.GroupLayout(signInP);
        signInP.setLayout(signInPLayout);
        signInPLayout.setHorizontalGroup(
            signInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        signInPLayout.setVerticalGroup(
            signInPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel2.add(signInP, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 347, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_building_50px.png")); // NOI18N
        jLabel6.setText("KTX PTIT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 1040, 44));

        panel.setBackground(new java.awt.Color(97, 212, 195));
        panel.setPreferredSize(new java.awt.Dimension(145, 49));

        signUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUp.setText("Đăng Ký");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel2.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 347, -1, -1));

        daDky.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        daDky.setForeground(new java.awt.Color(255, 255, 255));
        daDky.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daDky.setText("Đã từng đăng ký KTX");
        daDky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daDkyMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                daDkyMousePressed(evt);
            }
        });
        jPanel2.add(daDky, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 426, 145, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 442, 115, 10));

        xemTT.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        xemTT.setForeground(new java.awt.Color(255, 255, 255));
        xemTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xemTT.setText("Xem thông tin kí túc xá");
        xemTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xemTTMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                xemTTMousePressed(evt);
            }
        });
        jPanel2.add(xemTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 426, 155, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 442, 139, 10));

        daDky1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        daDky1.setForeground(new java.awt.Color(255, 255, 255));
        daDky1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daDky1.setText("Xem thông tin đã gửi đơn đăng ký");
        daDky1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daDky1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                daDky1MousePressed(evt);
            }
        });
        jPanel2.add(daDky1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 464, 1028, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 480, 196, 10));

        hide_show.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_eye_15px_1.png")); // NOI18N
        hide_show.setText(" ");
        hide_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide_showMousePressed(evt);
            }
        });
        jPanel2.add(hide_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        hide_show1.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_hide_15px_1.png")); // NOI18N
        hide_show1.setText(" ");
        hide_show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide_show1MousePressed(evt);
            }
        });
        jPanel2.add(hide_show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        String passUs =String.valueOf(jPass.getPassword());
        boolean check=false;
        int idRole=0;
       for(int i=0;i<list.size();i++)
       {
         if(list.get(i).getIDUs().equals(jAcc.getText())&&list.get(i).getPass().equals(passUs))
         {
             idRole=list.get(i).getIDRole();
             check=true;
         }
       }
        if(check==true){
         JOptionPane.showMessageDialog(rootPane, "Sign In Success!");
            setVisible(false);
            IDUs=jAcc.getText();
            if(idRole==1)
                new SinhVien().setVisible(true);
            else if(idRole==2)
                new Manager().setVisible(true);
            else new Admin().setVisible(true);
        }
        else 
             JOptionPane.showMessageDialog(rootPane, "MSSV OR PASSWORD IS NOT CORRECT. PLEASE TRY !");
        
    }//GEN-LAST:event_jLabel4MousePressed

    private void signInPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseEntered
        // TODO add your handling code here:
       // onHover(signInP);
    }//GEN-LAST:event_signInPMouseEntered

    private void signInPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_signInPMouseExited

    private void signInPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMouseReleased

    }//GEN-LAST:event_signInPMouseReleased

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
       // resetColor(jPanel3);
         resetColor(signInP);
         resetColor(panel);
         daDky.setForeground(new Color(255,255,255));
         xemTT.setForeground(new Color(255,255,255));
         daDky1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void signInPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPMousePressed
        // TODO add your handling code here:
        String passUs =String.valueOf(jPass.getPassword());
        boolean check=false;
        int idRole=0;
       for(int i=0;i<list.size();i++)
       {
         if(list.get(i).getIDUs().equals(jAcc.getText())&&list.get(i).getPass().equals(passUs))
         {
             idRole=list.get(i).getIDRole();
             check=true;
         }
       }
        if(check==true){
         JOptionPane.showMessageDialog(rootPane, "Sign In Success!");
            setVisible(false);
            IDUs=jAcc.getText();
            if(idRole==1)
                new SinhVien().setVisible(true);
            else if(idRole==2)
                new Manager().setVisible(true);
            else if(idRole==3){
                new Admin().setVisible(true);
            }
        }
        else 
             JOptionPane.showMessageDialog(rootPane, "MSSV OR PASSWORD IS NOT CORRECT. PLEASE TRY !");
    }//GEN-LAST:event_signInPMousePressed

    private void jAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAccActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        onHover(signInP);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void signUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseEntered
        // TODO add your handling code here:
        onHover(panel);
    }//GEN-LAST:event_signUpMouseEntered

    private void daDkyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daDkyMouseEntered
        // TODO add your handling code here:
        daDky.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_daDkyMouseEntered

    private void xemTTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemTTMouseEntered
        // TODO add your handling code here:
        xemTT.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_xemTTMouseEntered

    private void signUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new DangKyThongTin().setVisible(true);
    }//GEN-LAST:event_signUpMousePressed

    private void daDky1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daDky1MouseEntered
        // TODO add your handling code here:
        daDky1.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_daDky1MouseEntered

    private void daDky1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daDky1MousePressed
        // TODO add your handling code here:
        setVisible(false);
        new XemThongTinDKy().setVisible(true);
    }//GEN-LAST:event_daDky1MousePressed

    private void daDkyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daDkyMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_daDkyMousePressed

    private void xemTTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemTTMousePressed
        // TODO add your handling code here:
         try {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"D:\\word\\gioiThieuKTXpdf.pdf");
        } catch (Exception e) {
           e.printStackTrace();
        }
    }//GEN-LAST:event_xemTTMousePressed

    private void hide_showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide_showMousePressed
        // TODO add your handling code here:
        hide_show1.setVisible(true);
        hide_show.setVisible(false);
        jPass.setEchoChar((char)0);
    }//GEN-LAST:event_hide_showMousePressed

    private void hide_show1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide_show1MousePressed
        // TODO add your handling code here:
        hide_show.setVisible(true);
        hide_show1.setVisible(false);
        jPass.setEchoChar('\u25cf');
    }//GEN-LAST:event_hide_show1MousePressed

    /**
     * @param args the command line arguments
     */
    void onHover(JPanel panel){
        panel.setBackground(new Color(204,204,255));
    }
    void setColor(JPanel panel){
        panel.setBackground(new Color(36,47,65));
    }
   
    void resetColor(JPanel panel){
       
            panel.setBackground(new Color(97,212,195));
        
    }
     void onHo(JPanel panel){
        panel.setBackground(new Color(0,102,102));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daDky;
    private javax.swing.JLabel daDky1;
    private javax.swing.JLabel hide_show;
    private javax.swing.JLabel hide_show1;
    private javax.swing.JTextField jAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel signInP;
    private javax.swing.JLabel signUp;
    private javax.swing.JLabel xemTT;
    // End of variables declaration//GEN-END:variables
}
