/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Bill;
import model.Contract;
import model.Room;
import model.Student;
import model.TypeRoom;
import model.User;
import model.Zone;

/**
 *
 * @author VanTinh
 */
public class XemThongTinDKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKyThongTin
     */
    private ArrayList <Contract> listContract=new DAO().getListContract();
    private ArrayList <User> listUser=new DAO().getListUser();
    public XemThongTinDKy() {
        initComponents();
        setResizable(false);
        setVisiCheckTT();
        setLocation(200, 150);
          sdt.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
          cmnd.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
          Date d=new Date();
          int month=month(d);
          if(month>=8&&month<=12){
              motKi.setVisible(true);
              haiKi.setVisible(true);
              baKi.setVisible(true);
              motKiL.setVisible(true);
              haiKiL.setVisible(true);
              motKiL.setText("Học kì 1 - 5 tháng");
              haiKiL.setText("Học kì 1 và 2 - 10 tháng");
          }else if(month>=1&&month<=5){
              motKi.setVisible(true);
              haiKi.setVisible(true);
              baKi.setVisible(false);
              motKiL.setVisible(true);
              haiKiL.setVisible(true);
              motKiL.setText("Học kì 3 - 2 tháng");
              haiKiL.setText("Học kì 2 và 3 - 7 tháng");
          }else{
              motKi.setVisible(true);
              haiKi.setVisible(false);
              baKi.setVisible(false);
              motKiL.setVisible(true);
              haiKiL.setVisible(false);
              motKiL.setText("Học kì 3 - 2 tháng");
          }
          confirm.setVisible(false);
          cancel.setVisible(false);
          edit.setVisible(false);
          cancelDky.setVisible(false);
    }
     public Date setDate(Date date,String setDate){
  SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        try {
            date=df.parse(setDate);
        } catch (Exception e) {
        }
  return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        huyP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        hoTen = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        mssvLB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lop = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cmnd = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        danToc = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tonGiao = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        quocTich = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        diaChi = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        sdt = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        checkDate = new javax.swing.JLabel();
        checkSDT = new javax.swing.JLabel();
        checkClass = new javax.swing.JLabel();
        checkEmail = new javax.swing.JLabel();
        checkCMND = new javax.swing.JLabel();
        checkMSSV = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        namCheck = new javax.swing.JRadioButton();
        nuCheck = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        zoneComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        typeRoomComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        roomComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        motKi = new javax.swing.JRadioButton();
        haiKi = new javax.swing.JRadioButton();
        baKi = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        totalPayment = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        motKiL = new javax.swing.JLabel();
        haiKiL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nganh = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        mssvS = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        cancelDky = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        huyP.setBackground(new java.awt.Color(36, 47, 65));
        huyP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huyPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                huyPMouseEntered(evt);
            }
        });
        huyP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_building_50px.png")); // NOI18N
        jLabel1.setText("KTX PTIT");
        huyP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 6, 284, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 62, 914, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tìm kiếm thông tin:");
        huyP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 78, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ Và Tên");
        huyP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 118, 100, 28));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 164, 267, 10));

        hoTen.setEditable(false);
        hoTen.setBackground(new java.awt.Color(36, 47, 65));
        hoTen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hoTen.setForeground(new java.awt.Color(255, 255, 255));
        hoTen.setBorder(null);
        hoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenActionPerformed(evt);
            }
        });
        hoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hoTenKeyReleased(evt);
            }
        });
        huyP.add(hoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 148, 274, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 231, 267, 10));

        mssvLB.setEditable(false);
        mssvLB.setBackground(new java.awt.Color(36, 47, 65));
        mssvLB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mssvLB.setForeground(new java.awt.Color(255, 255, 255));
        mssvLB.setBorder(null);
        mssvLB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mssvLBKeyReleased(evt);
            }
        });
        huyP.add(mssvLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 215, 267, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mssv");
        huyP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 180, 75, 28));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lớp");
        huyP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 258, 75, 28));

        lop.setEditable(false);
        lop.setBackground(new java.awt.Color(36, 47, 65));
        lop.setForeground(new java.awt.Color(255, 255, 255));
        lop.setBorder(null);
        lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopActionPerformed(evt);
            }
        });
        huyP.add(lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 292, 267, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 308, 267, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CMND/CCCD");
        huyP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 28));

        cmnd.setEditable(false);
        cmnd.setBackground(new java.awt.Color(36, 47, 65));
        cmnd.setForeground(new java.awt.Color(255, 255, 255));
        cmnd.setBorder(null);
        huyP.add(cmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 366, 267, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 382, 267, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dân Tộc");
        huyP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 404, 143, 28));

        danToc.setEditable(false);
        danToc.setBackground(new java.awt.Color(36, 47, 65));
        danToc.setForeground(new java.awt.Color(255, 255, 255));
        danToc.setBorder(null);
        huyP.add(danToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 438, 267, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 454, 267, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tôn Giáo");
        huyP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 479, 133, 28));

        tonGiao.setEditable(false);
        tonGiao.setBackground(new java.awt.Color(36, 47, 65));
        tonGiao.setForeground(new java.awt.Color(255, 255, 255));
        tonGiao.setBorder(null);
        huyP.add(tonGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 512, 270, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 528, 270, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ngày Sinh");
        huyP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 122, 110, -1));

        ngaySinh.setEditable(false);
        ngaySinh.setBackground(new java.awt.Color(36, 47, 65));
        ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ngaySinh.setForeground(new java.awt.Color(255, 255, 255));
        ngaySinh.setBorder(null);
        huyP.add(ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 144, 282, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 282, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quốc Tịch");
        huyP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 186, 119, -1));

        quocTich.setEditable(false);
        quocTich.setBackground(new java.awt.Color(36, 47, 65));
        quocTich.setForeground(new java.awt.Color(255, 255, 255));
        quocTich.setBorder(null);
        huyP.add(quocTich, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 211, 282, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 229, 282, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Địa Chỉ");
        huyP.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 92, -1));

        diaChi.setEditable(false);
        diaChi.setBackground(new java.awt.Color(36, 47, 65));
        diaChi.setForeground(new java.awt.Color(255, 255, 255));
        diaChi.setBorder(null);
        diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiActionPerformed(evt);
            }
        });
        huyP.add(diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 288, 282, 20));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 308, 282, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        huyP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 324, 131, -1));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(36, 47, 65));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        huyP.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 346, 282, -1));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 362, 282, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ngành");
        huyP.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 466, 180, -1));

        sdt.setEditable(false);
        sdt.setBackground(new java.awt.Color(36, 47, 65));
        sdt.setForeground(new java.awt.Color(255, 255, 255));
        sdt.setBorder(null);
        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });
        huyP.add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 416, 280, -1));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 432, 282, 10));

        checkDate.setForeground(new java.awt.Color(255, 51, 0));
        checkDate.setText("Ngày sinh nhập theo ngày/tháng/năm");
        huyP.add(checkDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 166, 270, -1));

        checkSDT.setForeground(new java.awt.Color(255, 51, 0));
        checkSDT.setText("Thông tin không hợp lệ");
        huyP.add(checkSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 436, 280, 20));

        checkClass.setForeground(new java.awt.Color(255, 51, 0));
        checkClass.setText("Thông tin không hợp lệ");
        huyP.add(checkClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 316, 270, 20));

        checkEmail.setForeground(new java.awt.Color(255, 51, 0));
        checkEmail.setText("Thông tin không hợp lệ");
        huyP.add(checkEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 366, 270, 20));

        checkCMND.setForeground(new java.awt.Color(255, 51, 0));
        checkCMND.setText("Thông tin không hợp lệ");
        huyP.add(checkCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 270, 20));

        checkMSSV.setForeground(new java.awt.Color(255, 51, 0));
        checkMSSV.setText("Thông tin không hợp lệ hoặc MSSV này đã được sử dụng");
        huyP.add(checkMSSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 270, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_undo_30px_1.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        huyP.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_male_female_user_group_15px.png")); // NOI18N
        jLabel14.setText("Giới tính");

        namCheck.setBackground(new java.awt.Color(97, 212, 195));
        namCheck.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namCheck.setForeground(new java.awt.Color(0, 0, 0));
        namCheck.setText("Nam");
        namCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namCheckMousePressed(evt);
            }
        });
        namCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namCheckActionPerformed(evt);
            }
        });

        nuCheck.setBackground(new java.awt.Color(97, 212, 195));
        nuCheck.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nuCheck.setForeground(new java.awt.Color(0, 0, 0));
        nuCheck.setText("Nữ");
        nuCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuCheckMousePressed(evt);
            }
        });
        nuCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuCheckActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_flag_filled_20px.png")); // NOI18N
        jLabel15.setText("Khu");

        zoneComboBox.setBackground(new java.awt.Color(97, 212, 195));
        zoneComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        zoneComboBox.setForeground(new java.awt.Color(0, 0, 0));
        zoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneComboBoxActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_business_girl_hotel_room_15px_1.png")); // NOI18N
        jLabel16.setText("Loại phòng");

        typeRoomComboBox.setBackground(new java.awt.Color(97, 212, 195));
        typeRoomComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        typeRoomComboBox.setForeground(new java.awt.Color(0, 0, 0));
        typeRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dịch vụ loại 1 - 420k/1 tháng", "Dịch vụ loại 2 - 330k/1 tháng", "Loại thường- 120k/1 tháng" }));
        typeRoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRoomComboBoxActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_hotel_bed_15px.png")); // NOI18N
        jLabel17.setText("Room");

        roomComboBox.setBackground(new java.awt.Color(97, 212, 195));
        roomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboBoxActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_planner_20px_2.png")); // NOI18N
        jLabel20.setText("Thời hạn");

        motKi.setBackground(new java.awt.Color(97, 212, 195));
        motKi.setForeground(new java.awt.Color(0, 0, 0));
        motKi.setText("1 Kì");
        motKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                motKiMousePressed(evt);
            }
        });
        motKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motKiActionPerformed(evt);
            }
        });

        haiKi.setBackground(new java.awt.Color(97, 212, 195));
        haiKi.setForeground(new java.awt.Color(0, 0, 0));
        haiKi.setText("2 Kì");
        haiKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                haiKiMousePressed(evt);
            }
        });
        haiKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haiKiActionPerformed(evt);
            }
        });

        baKi.setBackground(new java.awt.Color(97, 212, 195));
        baKi.setForeground(new java.awt.Color(0, 0, 0));
        baKi.setText("3 Kì");
        baKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baKiMousePressed(evt);
            }
        });
        baKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baKiActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tổng tiền phải trả");

        totalPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalPayment.setForeground(new java.awt.Color(204, 0, 0));
        totalPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPayment.setText("0");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("đồng");

        motKiL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        motKiL.setForeground(new java.awt.Color(0, 0, 0));
        motKiL.setText("hoc ki");

        haiKiL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        haiKiL.setForeground(new java.awt.Color(0, 0, 0));
        haiKiL.setText("hoc ki");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nuCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(typeRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(motKi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(motKiL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(haiKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(haiKiL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(totalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(baKi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namCheck)
                    .addComponent(nuCheck))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(typeRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motKi)
                    .addComponent(motKiL))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haiKi)
                    .addComponent(haiKiL))
                .addGap(10, 10, 10)
                .addComponent(baKi)
                .addGap(15, 15, 15)
                .addComponent(jLabel21)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPayment)
                    .addComponent(jLabel23))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        huyP.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 144, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Số Điện Thoại");
        huyP.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 394, 184, -1));

        nganh.setEditable(false);
        nganh.setBackground(new java.awt.Color(36, 47, 65));
        nganh.setForeground(new java.awt.Color(255, 255, 255));
        nganh.setBorder(null);
        nganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nganhActionPerformed(evt);
            }
        });
        huyP.add(nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 496, 280, -1));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 512, 280, 10));

        mssvS.setBackground(new java.awt.Color(36, 47, 65));
        mssvS.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mssvS.setForeground(new java.awt.Color(255, 255, 255));
        mssvS.setBorder(null);
        mssvS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mssvSMouseClicked(evt);
            }
        });
        mssvS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mssvSActionPerformed(evt);
            }
        });
        mssvS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mssvSKeyReleased(evt);
            }
        });
        huyP.add(mssvS, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 81, 234, -1));

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        huyP.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 98, 234, 10));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Trạng Thái:");
        huyP.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 550, 75, 28));

        status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(204, 0, 0));
        huyP.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 550, 111, 28));

        confirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(0, 0, 0));
        confirm.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_checked_15px.png")); // NOI18N
        confirm.setText("Xác nhận");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        huyP.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 121, -1));

        cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 0, 0));
        cancel.setIcon(new javax.swing.ImageIcon("D:\\imagesProject\\icons8_cancel_20px.png")); // NOI18N
        cancel.setText("Hủy");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        huyP.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 124, -1));

        cancelDky.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelDky.setForeground(new java.awt.Color(0, 0, 0));
        cancelDky.setText("Hủy đăng ký");
        cancelDky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDkyActionPerformed(evt);
            }
        });
        huyP.add(cancelDky, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 120, -1));

        edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 0, 0));
        edit.setText("Chỉnh sửa");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        huyP.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 120, -1));

        getContentPane().add(huyP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenActionPerformed

    private void lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lopActionPerformed

    private void diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
public boolean addStudent(Student s){
     SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat df2=new SimpleDateFormat("ddMMyyyy");
            Date dateBirth=null;
 try {
             dateBirth=df.parse(ngaySinh.getText());
        } catch (Exception e) {
        }
        s.setHoTen(chuanHoa(hoTen.getText().toUpperCase()));
        s.setMssv(mssvLB.getText().toUpperCase());
        s.setAddress(diaChi.getText());
        s.setCmnd(cmnd.getText());
        s.setDateOfBirth(dateBirth);
        s.setGioiTinh(gioiTinh);
        s.setDanToc(danToc.getText());
        s.setQuocTich(quocTich.getText());
        s.setTonGiao(tonGiao.getText());
        s.setLop(lop.getText().toUpperCase());
        s.setEmail(email.getText());
        s.setSdt(sdt.getText());
        s.setIDUs(mssvLB.getText().toUpperCase());
        s.setCmnd(cmnd.getText());
        s.setNganh(nganh.getText());
        if(new DAO().addStudent(s)) return true;
        else return false;
}
boolean checkMSSV(String mssv){
    
    String check="^N[0-9]{2}\\w{4}[0-9]{3}";
    if(mssv.matches(check)) return true;
    else return false;
}
public boolean checkLop(String chuoi){
    String check="^D[0-9]{2}\\w{4}[0-9]{2}-N";
    if(chuoi.matches(check)) return true;
    else return false;
}
public boolean checkCMND(String chuoi){
    String check="\\d{9}";
    if(chuoi.matches(check)) return true;
    else return false;
}
public boolean checkEmail(String chuoi){
    String check="^n[0-9]{2}\\w{4}[0-9]{3}@student.ptithcm.edu.vn";
    if(chuoi.matches(check)) return true;
    else return false;
}
public boolean checkSDT(String chuoi){
    String check="0\\d{9,10}";
    if(chuoi.matches(check)) return true;
    else return false;
}
public boolean checkDate(String chuoi){
    String check="\\d{1,2}/\\d{1,2}/\\d{4}";
    if(chuoi.matches(check)) return true;
    else return false;
}
boolean addUser(User u){
    u.setIDUs(mssvLB.getText());
    SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat df2=new SimpleDateFormat("ddMMyyyy");
    Date d=null;
    try {
        d=df.parse(ngaySinh.getText());
    } catch (Exception e) {
    }
    u.setPass(df2.format(d));
    u.setIDRole(1);
    u.setStatus("Đang đợi duyệt");
    if(new DAO().addUser(u)) return true;
    return false;
}
boolean addContract(Contract c){
    ArrayList<Contract>listC=new DAO().getListContract();
     int size=listC.size();
     c.setIDContract(++size);
     c.setIDStudent(mssvLB.getText().toUpperCase());
     c.setIDStaff("GV1");
     String room=(String)roomComboBox.getSelectedItem();
     c.setIDRoom(room);
     Date d=new Date();
     c.setStartDay(d);
     String tgDky=kiDangKy;
     Date date=new Date();
     int year=year(date);
     if(tgDky.equalsIgnoreCase("HK1")){
         c.setFinishDay(setDate(d, "31-12-2021"));
         c.setAmountOfMonth(5);
     }
     else if(tgDky.equalsIgnoreCase("HK1-2")){
         c.setFinishDay(setDate(d, "31-05-"+String.valueOf(year+1)));
         c.setAmountOfMonth(10);
     }
     else if(tgDky.equalsIgnoreCase("HK2")){
         c.setFinishDay(setDate(d, "31-05-"+String.valueOf(year+1)));
         c.setAmountOfMonth(5);
     }
     else if(tgDky.equalsIgnoreCase("HK3")){
         c.setFinishDay(setDate(d, "31-07-"+String.valueOf(year+1)));
         c.setAmountOfMonth(2);
     }else if(tgDky.equalsIgnoreCase("HK2-3")){
         c.setFinishDay(setDate(d, "31-07-"+String.valueOf(year+1)));
         c.setAmountOfMonth(7);
     }else if(tgDky.equalsIgnoreCase("Cả năm")){
         c.setFinishDay(setDate(d, "31-07-"+String.valueOf(year+1)));
         c.setAmountOfMonth(12);
     }
     c.setPayment(cost);
     if(new DAO().addContract(c)) return true;
     return false;
}
public static String converter(int n){
           String data = String.valueOf(n);
           char[] arrData = data.toCharArray();
           String result = "";
           int length = arrData.length;
           int count =1;
           for(int i=length-1;i>=0;i--){
               result+=arrData[i];
              if(count++ == 3){
                  if(i!=0){
                  result+='.';
                  count=1;
                  }
              }
           }
           String finalResult = "";
           char[] resultData = result.toCharArray();
           for(int i=resultData.length-1;i>=0;i--){
               finalResult += resultData[i];
           }           
           return finalResult;
    }
boolean addBill(Bill b){
    ArrayList <Bill> list=new DAO().getListBillAll();
    SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    int size=list.size();
    b.setIDBill(++size);
    b.setIDStudent(mssvLB.getText());
    b.setIDStaff("GV1");
    b.setStatus("Chưa thanh toán");
    Date d=new Date();
    b.setDateCreate(d);
    Date ngayBD=new DAO().startDate(mssvLB.getText());
    Date ngayKT=new DAO().finishDate(mssvLB.getText().toUpperCase());
    b.setNoiDung("Tiền ở ktx từ "+df.format(ngayBD)+" đến "+df.format(ngayKT));
    b.setTypeBill("lệ phí");
    b.setSemester(kiDangKy);
    b.setPayment(cost);
    if(new DAO().addBill(b)) return true;
    else return false;
}
boolean checkMSSV_Duplicate(String mssv){
    for(User u:listUser){
        if(u.getIDUs().equals(mssv))
            return false;
    }
    return true;
}
boolean checkThongTin(){
    boolean check1=false;
    boolean check2=false;
    boolean check3=false;
    boolean check4=false;
    boolean check5=false;
    boolean check6=false;
    if(checkMSSV(mssvLB.getText().toUpperCase())){
        check1=true;
        checkMSSV.setVisible(false);
    }
    else checkMSSV.setVisible(true);
    if(checkLop(lop.getText().toUpperCase())){
        check2=true;
        checkClass.setVisible(false);
    }
    else checkClass.setVisible(true);
    if(checkCMND(cmnd.getText())){
        check3=true;
        checkCMND.setVisible(false);
    }
    else checkCMND.setVisible(true);
    if(checkEmail(email.getText().toLowerCase())){
        check4=true;
        checkEmail.setVisible(false);
    }
    else checkEmail.setVisible(true);
     if(checkSDT(sdt.getText())){
        check5=true;
        checkSDT.setVisible(false);
    }
    else checkSDT.setVisible(true);
     if(checkDate(ngaySinh.getText())){
         check6=true;
         checkDate.setVisible(false);
    }
    else checkDate.setVisible(true);
     if(check1==true&&check2==true&&check3==true&&check4==true&&check5==true&&check6==true)
         return true;
     else return false;
}
void setVisiCheckTT(){
    checkDate.setVisible(false);
    checkClass.setVisible(false);
    checkCMND.setVisible(false);
    checkEmail.setVisible(false);
    checkSDT.setVisible(false);
    checkMSSV.setVisible(false);
}
    private void huyPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huyPMouseEntered
        // TODO add your handling code here:
//        setColor(editP);
//        setColor(huyD);
    }//GEN-LAST:event_huyPMouseEntered
boolean checkTT_Dky(){
    if(!(namCheck.isSelected()||nuCheck.isSelected())) {
        JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn giới tính");
    }
    else{
        if(zoneComboBox.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn khu");
        }else{
            if(roomComboBox.getSelectedIndex()<0){
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn phòng");
            }else{
                if(!(motKi.isSelected()||haiKi.isSelected()||baKi.isSelected())){
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thời gian đăng ký");
                }else{
                    return true;
                }
            }
        }
    }
    return false;
}
    private void hoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hoTenKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hoTenKeyReleased

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        // TODO add your handling code here:
         email.setText(mssvLB.getText().toLowerCase());
    }//GEN-LAST:event_emailMousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        // TODO add your handling code here:
        setVisible(false);
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jLabel19MousePressed

    private void mssvLBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mssvLBKeyReleased
        // TODO add your handling code here:
        if(!nganh.getText().equals(""))
        email.setText(mssvLB.getText().toLowerCase()+"@student.ptithcm.edu.vn");
        String check1="N[1-9]{2}DCPT";
        String check2="N[1-9]{2}DCCN";
        String check3="N[1-9]{2}DCMR";
        String check4="N[1-9]{2}DCAT";
        String check5="N[1-9]{2}DCKT";
        String check6="N[1-9]{2}DCQT";
        String check7="N[1-9]{2}DCVT";
        String checkSo="[0-9]{1,3}";
        if(mssvLB.getText().toUpperCase().matches(check1)||mssvLB.getText().toUpperCase().matches(check1+checkSo))
            nganh.setText("Công Nghệ Đa Phương Tiện");
        else if(mssvLB.getText().toUpperCase().matches(check2)||mssvLB.getText().toUpperCase().matches(check2+checkSo))
            nganh.setText("Công Nghệ Thông Tin");
        else if(mssvLB.getText().toUpperCase().matches(check3)||mssvLB.getText().toUpperCase().matches(check3+checkSo))
            nganh.setText("Marketing");
        else if(mssvLB.getText().toUpperCase().matches(check4)||mssvLB.getText().toUpperCase().matches(check4+checkSo))
            nganh.setText("An Toàn Thông Tin");
        else if(mssvLB.getText().toUpperCase().matches(check5)||mssvLB.getText().toUpperCase().matches(check5+checkSo))
            nganh.setText("Kế Toán");
        else if(mssvLB.getText().toUpperCase().matches(check6)||mssvLB.getText().toUpperCase().matches(check6+checkSo))
            nganh.setText("Quản Trị Kinh Doanh");
        else if(mssvLB.getText().toUpperCase().matches(check7)||mssvLB.getText().toUpperCase().matches(check7+checkSo))
            nganh.setText("Điện Tử Viễn Thông");
       else nganh.setText("");
    }//GEN-LAST:event_mssvLBKeyReleased

    private void zoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneComboBoxActionPerformed
        // TODO add your handling code here:
        String zone=(String)zoneComboBox.getSelectedItem();
        String sexValue="";
        String typeValue=(String)typeRoomComboBox.getSelectedItem();
        if(namCheck.isSelected()) sexValue=namCheck.getText();
        else sexValue=nuCheck.getText();
        int sex,type;
        if(sexValue.equals("Nam")){
            sex=1;
        }
        else sex=2;
        if(typeValue.equals("Dịch vụ loại 1 - 420k/1 tháng")) type=1;
        else if(typeValue.equals("Dịch vụ loại 2 - 330k/1 tháng")) type =2;
        else type=3;
        setData(sex, zone, type);
        showTT_cost();
    }//GEN-LAST:event_zoneComboBoxActionPerformed
public void setData(int sex, String zone, int typeRoom){
        roomComboBox.removeAllItems();
        ArrayList<Room> arr = new DAO().getDataRoom(sex, zone, typeRoom);
        for (Room room: arr){
            roomComboBox.addItem(room.getNameRoom());
        }
    }
int cost=0;
    private void typeRoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRoomComboBoxActionPerformed
        // TODO add your handling code here:
        String zone=(String)zoneComboBox.getSelectedItem();
        String sexValue="";
        String typeValue=(String)typeRoomComboBox.getSelectedItem();
        if(namCheck.isSelected()) sexValue=namCheck.getText();
        else sexValue=nuCheck.getText();
        int sex,type;
        if(sexValue.equals("Nam")){
            sex=1;
        }
        else sex=2;
        if(typeValue.equals("Dịch vụ loại 1 - 420k/1 tháng")) type=1;
        else if(typeValue.equals("Dịch vụ loại 2 - 330k/1 tháng")) type =2;
        else type=3;
        setData(sex, zone, type);
        showTT_cost();
    }//GEN-LAST:event_typeRoomComboBoxActionPerformed
String kiDangKy="";
    private void haiKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haiKiActionPerformed
        // TODO add your handling code here:
        String room=(String)roomComboBox.getSelectedItem();
        cost=new DAO().getCost_NameRoom(room);
        if(haiKi.isSelected()){
            if(haiKiL.getText().equals("Học kì 1 và 2 - 10 tháng")){
                cost=cost*10;
                kiDangKy="HK1-2";
            }else if(haiKiL.getText().equals("Học kì 2 và 3 - 7 tháng")){
                kiDangKy="HK2-3";
                cost=cost*7;
            }
        }
        else cost=0;
        totalPayment.setText(converter(cost));
    }//GEN-LAST:event_haiKiActionPerformed
String gioiTinh="";
    private void namCheckMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namCheckMousePressed
        // TODO add your handling code here:
        ArrayList<Zone> listZoneNam=new DAO().getListZoneNam();
        nuCheck.setSelected(false);
        zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNam.size();i++)
        {
            zoneComboBox.addItem(listZoneNam.get(i).getNameZone());
        }
            if(namCheck.isSelected()) {
                zoneComboBox.removeAllItems();
        }else{
                gioiTinh="Nam";
            }
            showTT_cost();
    }//GEN-LAST:event_namCheckMousePressed

    private void nuCheckMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuCheckMousePressed
        // TODO add your handling code here:
        ArrayList<Zone> listZoneNu=new DAO().getListZoneNu();
        namCheck.setSelected(false);
        zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNu.size();i++)
        {
            zoneComboBox.addItem(listZoneNu.get(i).getNameZone());
        }
            if(nuCheck.isSelected()) {
            zoneComboBox.removeAllItems();
        }else{
                gioiTinh="Nữ";
            }
            showTT_cost();
    }//GEN-LAST:event_nuCheckMousePressed

    private void motKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motKiActionPerformed
        // TODO add your handling code here:
        String room=(String)roomComboBox.getSelectedItem();
         cost=new DAO().getCost_NameRoom(room);
        if(motKi.isSelected()){
            if(motKiL.getText().equals("Học kì 1 - 5 tháng")){
                kiDangKy="HK1";
                cost=cost*5;
            }else if(motKiL.getText().equals("Học kì 2 - 5 tháng")){
                kiDangKy="HK2";
                cost=cost*5;
            }else if(motKiL.getText().equals("Học kì 3 - 2 tháng")){
                kiDangKy="HK3";
                cost=cost*2;
            }
        }
        else cost=0;
        totalPayment.setText(converter(cost));
    }//GEN-LAST:event_motKiActionPerformed
void showTT_cost(){
    String room=(String)roomComboBox.getSelectedItem();
        cost=new DAO().getCost_NameRoom(room);
        if(motKi.isSelected()){
            if(motKiL.getText().equals("Học kì 1 - 5 tháng")){
                
                cost=cost*5;
            }else if(motKiL.getText().equals("Học kì 2 - 5 tháng")){
                cost=cost*5;
            }else if(motKiL.getText().equals("Học kì 3 - 2 tháng")){
                cost=cost*2;
            }
        }
        else if(haiKi.isSelected()){
            if(haiKiL.getText().equals("Học kì 1 và 2 - 10 tháng")){
                cost=cost*10;
            }else if(haiKiL.getText().equals("Học kì 2 và 3 - 7 tháng")){
                cost=cost*7;
            }
        }
        else if(baKi.isSelected()){
            cost=cost*12;
        }
        else cost=0;
        totalPayment.setText(converter(cost));
}
public String semester(){
    String semester="";
        if(motKi.isSelected()){
            if(motKiL.getText().equals("Học kì 1 - 5 tháng")){
                semester="HK1";
            }else if(motKiL.getText().equals("Học kì 2 - 5 tháng")){
                semester="HK2";
            }else if(motKiL.getText().equals("Học kì 3 - 2 tháng")){
                semester="HK3";
            }
        }
        else if(haiKi.isSelected()){
            if(haiKiL.getText().equals("Học kì 1 và 2 - 10 tháng")){
                semester="HK1-2";
            }else if(haiKiL.getText().equals("Học kì 2 và 3 - 7 tháng")){
                semester="HK2-3";
            }
        }
        else if(baKi.isSelected()){
            semester="Cả năm";
        }
        return kiDangKy;
}
int cost_Bill(){
    String semester="";
        if(motKi.isSelected()){
            if(motKiL.getText().equals("Học kì 1 - 5 tháng")){
                semester="HK1";
            }else if(motKiL.getText().equals("Học kì 2 - 5 tháng")){
                semester="HK2";
            }else if(motKiL.getText().equals("Học kì 3 - 2 tháng")){
                semester="HK3";
            }
        }
        else if(haiKi.isSelected()){
            if(haiKiL.getText().equals("Học kì 1 và 2 - 10 tháng")){
                semester="HK1-2";
            }else if(haiKiL.getText().equals("Học kì 2 và 3 - 7 tháng")){
                semester="HK2-3";
            }
        }
        else if(baKi.isSelected()){
            semester="Cả năm";
        }
    String room=(String)roomComboBox.getSelectedItem();
        cost=new DAO().getCost_NameRoom(room);
        if(motKi.isSelected()){
            if(semester.equals("HK1")){
                cost=cost*5;
            }else if(semester.equals("HK2")){
                cost=cost*5;
            }else if(semester.equals("HK3")){
                cost=cost*2;
            }
        }
        else if(haiKi.isSelected()){
            if(semester.equals("HK1-2")){
                cost=cost*10;
            }else if(semester.equals("Hk2-3")){
                cost=cost*7;
            }
        }
        else if(baKi.isSelected()){
            cost=cost*12;
        }
        else cost=0;
        return cost;
}

    private void baKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baKiActionPerformed
        // TODO add your handling code here:
        String room=(String)roomComboBox.getSelectedItem();
        int cost=new DAO().getCost_NameRoom(room);
        if(baKi.isSelected()){
            kiDangKy="Cả năm";
            cost=cost*12;
        }
        else cost=0;
        totalPayment.setText(converter(cost));
    }//GEN-LAST:event_baKiActionPerformed

    private void motKiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motKiMousePressed
        // TODO add your handling code here:
        haiKi.setSelected(false);
        baKi.setSelected(false);
    }//GEN-LAST:event_motKiMousePressed

    private void haiKiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haiKiMousePressed
        // TODO add your handling code here:
        motKi.setSelected(false);
        baKi.setSelected(false);
    }//GEN-LAST:event_haiKiMousePressed

    private void baKiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baKiMousePressed
        // TODO add your handling code here:
        haiKi.setSelected(false);
        motKi.setSelected(false);
    }//GEN-LAST:event_baKiMousePressed

    private void namCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namCheckActionPerformed

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboBoxActionPerformed
        // TODO add your handling code here:
        showTT_cost();
    }//GEN-LAST:event_roomComboBoxActionPerformed

    private void huyPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huyPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_huyPMouseClicked

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void nganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nganhActionPerformed

    private void mssvSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mssvSActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mssvSActionPerformed

    private void mssvSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mssvSKeyReleased
        // TODO add your handling code here:
        status.setText(new DAO().status_user(mssvS.getText()));
        if(new DAO().check_Us(mssvS.getText().toUpperCase())){
        if(status.getText().equals("Đang hoạt động")){
            edit.setVisible(false);
            cancelDky.setVisible(false);
            showTT_student(mssvS.getText());
        }else if(status.getText().equals("Đang đợi duyệt")){
            edit.setVisible(true);
            cancelDky.setVisible(true);
            showTT_student(mssvS.getText());
        }
        }
        else{
            edit.setVisible(false);
            cancelDky.setVisible(false);
            resetTT();
        }  
        confirm.setVisible(false);
        cancel.setVisible(false);
    }//GEN-LAST:event_mssvSKeyReleased

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(hoTen.getText().equals("")||mssvLB.getText().equals("")||lop.getText().equals("")||cmnd.getText().equals("")||danToc.getText().equals("")
                ||tonGiao.getText().equals("")||quocTich.getText().equals("")||diaChi.getText().equals("")||email.getText().equals("")
                ||sdt.getText().equals("")||ngaySinh.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
        }else{
            if(checkThongTin()){
                if(checkTT_Dky()){
                int x=JOptionPane.showConfirmDialog(rootPane, "Xác nhận thông tin chỉnh sửa?");
                if(x==JOptionPane.YES_OPTION){
                    if(update_Student(mssvS.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thành công");
                        setEdit(false);
                    }
                    else JOptionPane.showMessageDialog(rootPane, "Có lỗi vui lòng thử lại sau");
                }
                }
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void nuCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuCheckActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        setEdit(true);
        hoTen.requestFocus();
        confirm.setVisible(true);
        cancel.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        confirm.setVisible(false);
        cancel.setVisible(false);
        setEdit(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void mssvSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mssvSMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mssvSMouseClicked

    private void cancelDkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDkyActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(rootPane, "Chắc chắn hủy đăng ký?");
        if(x==JOptionPane.YES_OPTION){
            
            if(new DAO().deleteBill(mssvS.getText())
            &&new DAO().deleteContract(mssvS.getText())
            &&new DAO().deleteStudent(mssvS.getText())
            &&new DAO().deleteUser(mssvS.getText())){
                resetTT();
                mssvS.setText("");
                JOptionPane.showMessageDialog(rootPane, "Hủy đăng ký thành công");
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Hủy đăng ký thất bại. Vui lòng thử lại sau");
            }
        }
    }//GEN-LAST:event_cancelDkyActionPerformed

    void setEdit(boolean choose){
        hoTen.setEditable(choose);
        nganh.setEditable(choose);
        quocTich.setEditable(choose);
        tonGiao.setEditable(choose);
        lop.setEditable(choose);
        cmnd.setEditable(choose);
        danToc.setEditable(choose);
        ngaySinh.setEditable(choose);
        diaChi.setEditable(choose);
        email.setEditable(choose);
        sdt.setEditable(choose);
    }
    boolean update_Student(String idsv){
        Date d=null;
                    SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
                    SimpleDateFormat df2=new SimpleDateFormat("yyyyMMdd");
                    Student s=new Student();
                    try {
                        d=(df.parse(ngaySinh.getText()));
                    } catch (Exception e) {
                    }
                    s.setDateOfBirth((java.sql.Date) new java.sql.Date(d.getTime()));
                    s.setHoTen(hoTen.getText());
                    s.setLop(lop.getText());
                    if(namCheck.isSelected())
                        s.setGioiTinh("Nam");
                    else s.setGioiTinh("Nữ");
                    s.setSdt(sdt.getText());
                    s.setEmail(email.getText());
                    s.setAddress(diaChi.getText());
                    s.setDanToc(danToc.getText());
                    s.setTonGiao(tonGiao.getText());
                    s.setQuocTich(quocTich.getText());
                    s.setCmnd(cmnd.getText());
                    s.setNganh(nganh.getText());
                    s.setMssv(mssvLB.getText());
                    String semester="";
                    String room=(String)roomComboBox.getSelectedItem();
                    int payment=new DAO().getCost_NameRoom(room);
                    int amount=0;
                    if(motKi.isSelected()){
                        if(motKiL.getText().equals("Học kì 1 - 5 tháng")){
                            semester="HK1";
                            amount=5;
                            payment=payment*5;
                        }else if(motKiL.getText().equals("Học kì 2 - 5 tháng")){
                            semester="HK2";
                            payment=payment*5;
                            amount=5;
                        }else if(motKiL.getText().equals("Học kì 3 - 2 tháng")){
                            semester="HK3";
                             payment=payment*2;
                        }
                    }
                    else if(haiKi.isSelected()){
                        if(haiKiL.getText().equals("Học kì 1 và 2 - 10 tháng")){
                            semester="HK1-2";
                            payment=payment*10;
                            amount=10;
                        }else if(haiKiL.getText().equals("Học kì 2 và 3 - 7 tháng")){
                            semester="HK2-3";
                            payment=payment*7;
                            amount=7;
                        }
                    }
                    else if(baKi.isSelected()){
                        semester="Cả năm";
                         payment=payment*12;
                         amount=12;
                    }
                    Date ngayBD=new Date();
                    int year=year(ngayBD);
                    String finishDay="";
                    if(semester.equalsIgnoreCase("HK1")){
                        finishDay=year+"1231";
                    }
                    else if(semester.equalsIgnoreCase("HK1-2")){
                        finishDay=(year+1)+"0531";
                    }
                    else if(semester.equalsIgnoreCase("HK2")){
                        finishDay=(year+1)+"0531";
                    }
                    else if(semester.equalsIgnoreCase("HK2-3")||semester.equalsIgnoreCase("Cả năm")){
                        finishDay=(year+1)+"0731";
                    }else if(semester.equalsIgnoreCase("HK3")){
                        finishDay=year+"0731";
                    }
                    if(new DAO().updateStudent(s)) {
                        if(new DAO().update_Contract(idsv,df2.format(ngayBD),finishDay,(String)roomComboBox.getSelectedItem(),payment,amount)){
                            Date ngayKT=new DAO().finishDate(mssvS.getText().toUpperCase());
                             String noiDung="Tiền ở ktx từ "+df.format(ngayBD)+" đến "+df.format(ngayKT);
                        if(new DAO().update_Bill(idsv,payment , semester, noiDung, df2.format(ngayBD))){
                            return true;
                        }
                        }
                    }
                    return false;
    }
    
    void resetTT(){
    ngaySinh.setText("");
    namCheck.setSelected(false);
    nuCheck.setSelected(false);
    zoneComboBox.removeAllItems();
    roomComboBox.removeAllItems();
    motKi.setSelected(false);
    haiKi.setSelected(false);
    baKi.setSelected(false);
    totalPayment.setText("0");
    hoTen.setText(" ");
    mssvLB.setText(" ");
    lop.setText(" ");
    cmnd.setText(" ");
    sdt.setText(" ");
    email.setText(" ");
    quocTich.setText(" ");
    tonGiao.setText(" ");
    danToc.setText(" ");
    diaChi.setText(" ");
    sdt.setText(" ");
    nganh.setText(" ");
}
    void showTT_student(String idsv){
        Student s=new DAO().getStudent(idsv);
        hoTen.setText(s.getHoTen());
        mssvLB.setText(s.getMssv());
        lop.setText(s.getLop());
        cmnd.setText(s.getCmnd());
        danToc.setText(s.getDanToc());
        quocTich.setText(s.getQuocTich());
        tonGiao.setText(s.getTonGiao());
        if(!hoTen.getText().equals("")){
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        ngaySinh.setText(df.format(s.getDateOfBirth()));
        }
        diaChi.setText(s.getAddress());
        email.setText(s.getEmail());
        sdt.setText(s.getSdt());
        nganh.setText(s.getNganh());
        status.setText(new DAO().status_user(idsv));
        if(!hoTen.getText().equals("")){
        if(s.getGioiTinh().equals("Nam")) namCheck.setSelected(true);
        else nuCheck.setSelected(true);
        String room=new DAO().nameRoom(idsv);
        String type=new DAO().typeRoom(room);
        if(type.equals("dịch vụ loại 1")) typeRoomComboBox.setSelectedIndex(0);
        else if(type.equals("dịch vụ loại 2")) typeRoomComboBox.setSelectedIndex(1);
        else typeRoomComboBox.setSelectedIndex(2);
        // addZone
        if(namCheck.isSelected()){
        ArrayList<Zone> listZoneNam=new DAO().getListZoneNam();
        nuCheck.setSelected(false);
        zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNam.size();i++)
        {
            zoneComboBox.addItem(listZoneNam.get(i).getNameZone());
        }
        }else if(nuCheck.isSelected()){
            ArrayList<Zone> listZoneNu=new DAO().getListZoneNu();
            zoneComboBox.removeAllItems();
            for(int i=0;i<listZoneNu.size();i++)
        {
            zoneComboBox.addItem(listZoneNu.get(i).getNameZone());
        }
        }
        // addRoom
        String zone=(String)zoneComboBox.getSelectedItem();
        String sexValue="";
        String typeValue=(String)typeRoomComboBox.getSelectedItem();
        if(namCheck.isSelected()) sexValue=namCheck.getText();
        else sexValue=nuCheck.getText();
        int sex1,type1;
        if(sexValue.equals("Nam")){
            sex1=1;
        }
        else sex1=2;
        if(typeValue.equals("Dịch vụ loại 1 - 420k/1 tháng")) type1=1;
        else if(typeValue.equals("Dịch vụ loại 2 - 330k/1 tháng")) type1 =2;
        else type1=3;
        setData(sex1, zone, type1);
        zoneComboBox.setSelectedItem(new DAO().zone(room));
        roomComboBox.setSelectedItem(room);
        String semester=new DAO().getSemester(idsv);
        if(semester.equals("HK1")) motKi.setSelected(true);
        else if(semester.equals("HK2")) motKi.setSelected(true);
        else if(semester.equals("HK3"))motKi.setSelected(true);
        else if(semester.equals("HK1-2")) haiKi.setSelected(true);
        else if(semester.equals("HK2-3")) haiKi.setSelected(true);
        else if(semester.equals("Cả năm")) baKi.setSelected(true);
        }
        totalPayment.setText(converter(new DAO().totalPayment(idsv)));
    }

    int month(Date d){
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        String date=df.format(d);
        String arr[]=date.split("/");
        int month=Integer.valueOf(arr[1]);
        return month;
    }
int year(Date d){
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        String date=df.format(d);
        String arr[]=date.split("/");
        int month=Integer.valueOf(arr[2]);
        return month;
    }
 void setColor(JPanel panel){
        panel.setBackground(new Color(36,47,65));
    }
   
    void resetColor(JPanel panel){
       
            panel.setBackground(new Color(97,212,195));
        
    }
    void onHover(JPanel panel){
        panel.setBackground(new Color(0,102,102));
    }
   
    void leaveHover(JPanel panel){
        panel.setBackground(new Color(97,212,195));
    }
    public String chuanHoa(String s) {
        s = s.trim();
        s = s.replaceAll("\\s+", " ");

        String a[] = s.split(" ");
        String kq = "";
        for (String x : a) {
            kq = kq + x.substring(0,1).toUpperCase()+x.substring(1).toLowerCase();
            kq += " ";
        }
        kq = kq.trim();
        return kq;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemThongTinDKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemThongTinDKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemThongTinDKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemThongTinDKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemThongTinDKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baKi;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancelDky;
    private javax.swing.JLabel checkCMND;
    private javax.swing.JLabel checkClass;
    private javax.swing.JLabel checkDate;
    private javax.swing.JLabel checkEmail;
    private javax.swing.JLabel checkMSSV;
    private javax.swing.JLabel checkSDT;
    private javax.swing.JTextField cmnd;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField danToc;
    private javax.swing.JTextField diaChi;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton haiKi;
    private javax.swing.JLabel haiKiL;
    private javax.swing.JTextField hoTen;
    private javax.swing.JPanel huyP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lop;
    private javax.swing.JRadioButton motKi;
    private javax.swing.JLabel motKiL;
    private javax.swing.JTextField mssvLB;
    private javax.swing.JTextField mssvS;
    private javax.swing.JRadioButton namCheck;
    private javax.swing.JTextField nganh;
    private javax.swing.JTextField ngaySinh;
    private javax.swing.JRadioButton nuCheck;
    private javax.swing.JTextField quocTich;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JTextField sdt;
    private javax.swing.JLabel status;
    private javax.swing.JTextField tonGiao;
    private javax.swing.JLabel totalPayment;
    private javax.swing.JComboBox<String> typeRoomComboBox;
    private javax.swing.JComboBox<String> zoneComboBox;
    // End of variables declaration//GEN-END:variables
}
